baseURL = 'https://yochev.net/'
languageCode = 'en-gb'
theme = 'nightfall'
title = 'My New Hugo Site'

# [module]
# [[module.imports]]
# path = 'github.com/LordMathis/hugo-theme-nightfall'

[params]
hostname = "yochev.net"
user = "kristiyan"

[params.author]
email = "kris.yochev@gmail.com"
name = "Kristiyan Yochev"

[[params.social]]
key = 0
name = "email"
url = "mailto:kris.yochev@gmail.com"

[menu]
[[menu.header]]
name = "about"
url = "about"
weight = 2

[[menu.header]]
name = "posts"
url = "posts"
weight = 1
